[project]
name = "lab-1-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "m-djabali-ece", email = "messade.djabali@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
lab-1-uv = "lab_1_uv:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
